include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = LookinLoader2

LookinLoader2_FILES = MKLLRootListController.m
LookinLoader2_FRAMEWORKS = UIKit
LookinLoader2_PRIVATE_FRAMEWORKS = Preferences
RevealLoader2_EXTRA_FRAMEWORKS = AltList
LookinLoader2_INSTALL_PATH = /Library/PreferenceBundles
LookinLoader2_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
